daeger:
    volumes:
     - ./:/usr/local/src/github.con/apeltzer/deager/ 
     - /var/run/docker.sock:/var/run/docker.sock
     - ~/data/:/data/
     - ~/gatk/:/gatk/
    image: ubuntu:15.10 
    command: /usr/local/src/github.con/apeltzer/deager/amd64/build.sh
    environment:
     - GOPATH=/usr/local/
